### PR TITLE
Mint 3d Objects Thumbnail

### PR DESCRIPTION
**Pull request by alejoviola**

### CODE REVIEW

**Comment by alejoviola** [comment]
Isn't a final work

**Comment by colbr** [comment]
> Isn't a final work

No worries - do you want me to switch this to a Draft PR for now?

**Comment by colbr** [comment]
@alejoviola any updates on this one? I might close the PR for now if it's not being actively worked on just to clear up the PR list :)

**Comment by alejoviola** [comment]
@colbr I have to talk with Zachary about how to solve the backend, but close the PR and I'll open it again when I'm on it

**Pull request closed without merging**
