### PR TITLE
feat(rinkeby-support): update dApp to support rinkeby test network

### PR DESCRIPTION
**Pull request by padala**
[Associated Notion Card](https://www.notion.so/Rinkeby-Testnet-Deployment-02325984af284f2896368288854f9ec1)

-----

## 1. Pull request checklist

- [ ] Notion card has been moved to the Code Review column
- [ ] Notion card has a link to this PR
- [ ] A reviewer has been assigned to the Notion card

### CODE REVIEW

**Review by colbr — COMMENTED** [review]
Hey @padala,

Looking good. I managed to run things locally and saw that Rinkeby was connecting up fine, with a few errors which seem to be coming from the SDK. I'm sure you're aware of these.

Please note the preview build is throwing an error:
`Uncaught TypeError: Failed to construct 'URL': Invalid URL`

**Comment by padala** [comment]
@colbr  I didn't have this error earlier. I'll check and fix this. Thanks

**Comment by colbr** [comment]
This is looking good @padala, how far off is it from being finished?

**Comment by Remscar** [comment]
Please update zns-sdk to version v0.1.2 @padala

**Comment by padala** [comment]
@Remscar Updated `zns-sdk` to version `v0.1.2`

**Comment by colbr** [comment]
Hey @padala it's looking like the staking pages aren't loading on Rinkeby. I understand you're busy with another feature - would you like me to look into this?

**Review by colbr — APPROVED** [review]

**Comment by padala** [comment]
@colbr  Can we merge this?

**Pull request merged**
