### PR TITLE
Switch font to Inter

### PR DESCRIPTION
**Pull request by colbr**
- Changed font to Inter per new Figma doc
- Tweaked sizes and weights to be as consistent as possible with the new Figma doc

QA Instructions
https://www.loom.com/share/335049d74808436cb9d47696525f127c
(I said in the Loom that I would link the Figma, but I need confirmation I can link it in a public facing place - dm me if you need it)

### CODE REVIEW

**Comment by Remscar** [comment]
@colbr Can we get the conflicts in this fixed and then merge this?

**Comment by colbr** [comment]
> @colbr Can we get the conflicts in this fixed and then merge this?

Yep no worries - I'll just get design approval

**Comment by colbr** [comment]
@Remscar There's a couple of loose ends with some of the breakpoints after switching fonts, I'll wrap those up

**Review by EthFish — CHANGES_REQUESTED** [review]
Fixes needed listed [here](https://www.notion.so/ZNS-Inter-QA-Fixes-2e1fb09213b64f0b8fce30c764a95a14). If in doubt, check Figma frames on [here](https://www.figma.com/file/0zFJaRNODss8lxwRygUh24/UI-Wilder-Market?node-id=5631%3A189263)

**Comment by colbr** [comment]
> Fixes needed listed [here](https://www.notion.so/ZNS-Inter-QA-Fixes-2e1fb09213b64f0b8fce30c764a95a14). If in doubt, check Figma frames on [here](https://www.figma.com/file/0zFJaRNODss8lxwRygUh24/UI-Wilder-Market?node-id=5631%3A189263)

**ZNS Bar**
- [x] ZNS Bar text → 16px Reg for inactive and 16px bold for active
- [x] Equal padding around 'everything'

**NFT Preview**
- [x] story → 16px Reg
- [x] address & label for owner & creator → 16px Reg
- [x] ZNS Address below title → 16px Reg

**Root View -  List**
- [x] All list cell text → 16px Reg
- [x] ZNS Addresses below NFT Name in first column of list view → 14px Reg
- [x] Table header text - change to 14px Bold

**Root View - Grid**
- [x] NFT name → 24px Bold
- [x] ZNS Address below name → 16px Reg
- [x] 'Highest Bid' Label → 12px Reg 

**NFT View**
- [x] ZNS Address below title → 16px Reg
- [x] address & label for owner & creator → 16px Reg
- [x] Story → 16px
- [x] History → 16px
- [x] 'Highest Bid' and USD value → 16px Reg --- Noticed in the design that the USD amount was 18px, so I went with that
- [x] highest bid number value → 24px Bold

**Profile**
[x] Text in filter buttons beside search input → 16px Reg

**List**
[x] All table text to follow same instruction as given above for Root View List 
[x] OTHER than Status column of offers tab (i'm guessing 16px will be too big for this, if not, put up to 16px) --- 16px was fine here
Screenshot from 2021-09-07 20-49-40

**Grid**
[x] Same instruction as given above for Root View Grid

**Wizards**
[x] [See this figma frame for general appearance](https://www.figma.com/file/0zFJaRNODss8lxwRygUh24/UI-Wilder-Market?node-id=5635%3A942394)

**Modals**
[x] All Informational text → 16px Reg [See this figma frame for general appearance](https://www.figma.com/file/0zFJaRNODss8lxwRygUh24/UI-Wilder-Market?node-id=5635%3A942400)

**Review by EthFish — CHANGES_REQUESTED** [review]
**NFT Preview**
Add padding between story and buttons:
Screen Shot 2021-09-08 at 10 37 21 AM

**Profile - Offers Page**
Filter text should be Reg, not Bold

**Comment by colbr** [comment]
Commits between this comment and @EthFish 's comment above approved in zer0 by @EthFish

**Pull request merged**
