### PR TITLE
Improvements to Accept Bid flow

### PR DESCRIPTION
**Pull request by colbr**
[Associated Notion Card](https://www.notion.so/Add-error-messaging-to-Accept-Bid-flow-9a72f039b4bd48759dce00b3d8a576d7)

-----

## 1. Pull request checklist

- [x] Notion card has been moved to the Code Review column
- [x] Notion card has a link to this PR
- [x] A reviewer has been assigned to the Notion card

## 2. PR type
 

Feature

## 3. What is the old behaviour?

If accepting a bid failed for whatever reason, the Accept Bid UI would be stuck on 'Pending'.

## 4. What is the new behaviour?

If a bid fails, the UI returns back to the "Accept Bid" screen with an error message. Unfortunately at this stage, we can not tell exactly why a bid failed *unless* it was because the bidder has insufficient balance. If the bidder has insufficient balance, the user will get a descriptive message, otherwise the UI will just say "Failed to accept bid".

## 5. Other information

There are a few things that need to be done to get the codebase in a state where we can get the reason a bid failed to accept - we can return to this when those changes have been made.

Also, `OwnedDomainsTable.tsx` will need quite a large refactor. It's not very pretty. I will make a new task for that!

### CODE REVIEW

**Comment by colbr** [comment]
Looks like that merge broke some things for some reason 🤷

I'll look at this in the morning

**Review by padala — APPROVED** [review]

**Review by EthFish — APPROVED** [review]
Nice solution here B

**Comment by padala** [comment]
@colbr  there are some lint errors in the develop branch (probably happened during earlier merges) and it caused the checks to fail.

**Comment by colbr** [comment]
Difficult merge, moved to #372

**Pull request closed without merging**
